PACKET_TIMEOUT = 10     # 10 s
CHECK_PROBABILITY = 0.1     # 10%
SUBSCRIBE_TIMEOUT = 60 * 5  # 5 mins
SUBSCRIBE_INTERVAL = 60 * 2.4   # 2.4 mins
RSA_KEY_BITS = 512
HASH_METHOD = 'SHA-256'
HASH_LEN = 32
TIMESTAMP_LEN = 16
RSA_KEY_ID_BITS = 64
SIGNATURE_LEN = 64

SUBSCRIBE = 'SUBSCRIBE'
UNSUBSCRIBE = 'UNSUBSCRIBE'
INSIDE = 'INSIDE'
OUTSIDE = 'OUTSIDE'

SHUTDOWN_TIME = 1
